import type { Track } from "@townbus/engine";

/**
 * The playlist. This file *is* the product — engineering is the easy half.
 *
 * Inclusion filter: it has to be a song you'd hear distorted through a blown
 * speaker over engine noise on a TN town bus, not merely a good song of the
 * era. The spine is Ilaiyaraaja's 80s and early-90s folk and melody — what
 * actually played on those buses — with the 90s/2000s kuthu that took over the
 * back seat layered on top.
 *
 * Curated upstream as a Spotify playlist and resolved to video IDs by
 * `bun run sync-playlist`; every `youtubeId` points at a label, studio or
 * composer upload wherever one exists, because those are the ones that stay up.
 * CI runs `bun run check-tracks` to prove each still resolves and still embeds.
 *
 * Curation is PR-based: open a PR against this file. Kept in chronological
 * order so the era spread stays visible at a glance.
 */
export const tracks: readonly Track[] = [
  {
    youtubeId: "jgWmPZxW_ck",
    title: "Nee Thane Enthan Pon Vasantham",
    titleTa: "நீதானே எந்தன் பொன் வசந்தம்",
    movie: "Ninaivellam Nithya",
    year: 1982,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "alRD1Zvyl7M",
    title: "Chinna Ponnu Selai",
    titleTa: "சின்ன பொண்ணு சேலை",
    movie: "Malaiyur Mambattiyan",
    year: 1983,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "fwS9h9VbLXQ",
    title: "Poththi Vacha Malli Mottu",
    titleTa: "பொத்தி வச்ச மல்லி மொட்டு",
    movie: "Mann Vasanai",
    year: 1983,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "NlGMgfvv_T4",
    title: "Chittukku Chella Chittukku",
    titleTa: "சிட்டுக்கு செல்ல சிட்டுக்கு",
    movie: "Nallavanukku Nallavan",
    year: 1984,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "MFVnmfCqVXg",
    title: "Unnaithane Thanjam",
    titleTa: "உன்னைத்தானே தஞ்சம்",
    movie: "Nallavanukku Nallavan",
    year: 1984,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "fQnnsHcWDdI",
    title: "Vechukava Unna Mattum",
    titleTa: "வெச்சுக்கவா உன்ன மட்டும்",
    movie: "Nallavanukku Nallavan",
    year: 1984,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "e61Om4hO6oI",
    title: "Kaadhalin Deepam Ondru",
    titleTa: "காதலின் தீபம் ஒன்று",
    movie: "Thambikku Entha Ooru",
    year: 1984,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "TRrlFvMz-9I",
    title: "Azhagu Malaraada",
    titleTa: "அழகு மலராட",
    movie: "Vaidehi Kathirunthal",
    year: 1984,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "FjJHlThsJIM",
    title: "Kaathirunthu Kaathirunthu",
    titleTa: "காத்திருந்து காத்திருந்து",
    movie: "Vaidehi Kathirunthal",
    year: 1984,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "KNkAtDN9_1w",
    title: "Vaanile Thenila",
    titleTa: "வானிலே தென்னிலா",
    movie: "Kakki Chattai",
    year: 1985,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "pnym9PtIP3w",
    title: "Antha Nilava Thaan",
    titleTa: "அந்த நிலாவ தான்",
    movie: "Muthal Mariyathai",
    year: 1985,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "nyJQKjTeDKY",
    title: "Poongatru Thirumbuma",
    titleTa: "பூங்காற்று திரும்புமா",
    movie: "Muthal Mariyathai",
    year: 1985,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "Ja9EGWNKdGw",
    title: "Oorai Therinjikitten",
    titleTa: "ஊரைத் தெரிஞ்சுக்கிட்டேன்",
    movie: "Padikkadavan",
    year: 1985,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "kuthu",
  },
  {
    youtubeId: "58lxE6S-uGo",
    title: "Oru Koottu Kiliyaga",
    titleTa: "ஒரு கூட்டு கிளியாக",
    movie: "Padikkathavan",
    year: 1985,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "tCYlT1ipaZU",
    title: "Naan Oru Sindhu",
    titleTa: "நான் ஒரு சிந்து",
    movie: "Sindhu Bhairavi",
    year: 1985,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "d_hkDEbAvIc",
    title: "Chinnamani Kuyile",
    titleTa: "சின்னமணி குயிலே",
    movie: "Amman Kovil Kizhakale",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "lOguVQDHook",
    title: "Poove Eduthu",
    titleTa: "பூவே எடுத்து",
    movie: "Amman Kovil Kizhakale",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "V0naKtkSz2g",
    title: "Adi Aathadi",
    titleTa: "அடி ஆத்தாடி",
    movie: "Kadalora Kavithaigal",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "ehqNZ82t8nM",
    title: "Kodiyile Malliyapoo",
    titleTa: "கொடியிலே மல்லியப்பூ",
    movie: "Kadalora Kavithaigal",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "REzVhJ2ES_A",
    title: "Ooru Sanam Thoongirichu",
    titleTa: "ஊரு சனம் தூங்கிரிச்சு",
    movie: "Mella Thiranthathu Kadhavu",
    year: 1986,
    composer: "M. S. Viswanathan",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "jPTdHvUMs6M",
    title: "Vaa Vennila",
    titleTa: "வா வெண்ணிலா",
    movie: "Mella Thiranthathu Kadhavu",
    year: 1986,
    composer: "M. S. Viswanathan",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "NNLzxnmXrvc",
    title: "Chinna Chinna Vanna Kuyil",
    titleTa: "சின்ன சின்ன வண்ண குயில்",
    movie: "Mouna Ragam",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "8NHuGaFauRg",
    title: "Panivizhum Iravu",
    titleTa: "பனி விழும் இரவு",
    movie: "Mouna Ragam",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "rmOSlaUD5jY",
    title: "Enna Satham Indha Neram",
    titleTa: "என்ன சத்தம் இந்த நேரம்",
    movie: "Punnagai Mannan",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "orzCd4NKFZ0",
    title: "En Jodi Manja Kuruvi",
    titleTa: "என் ஜோடி மஞ்ச குருவி",
    movie: "Vikram",
    year: 1986,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "kuthu",
  },
  {
    youtubeId: "cDRfjIPZBsA",
    title: "Madura Marikkozhunthu",
    titleTa: "மதுர மரிக்கொழுந்து",
    movie: "Enga Ooru Pattukaran",
    year: 1987,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "fuEcN6iv4gs",
    title: "Shenbagame Shenbagame",
    titleTa: "செண்பகமே செண்பகமே",
    movie: "Enga Ooru Pattukaran",
    year: 1987,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "TmUJ7bVrwB4",
    title: "Thenpandi Thamizhe",
    titleTa: "தென்பாண்டித் தமிழே",
    movie: "Nayakan",
    year: 1987,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "VhKz3PF9iw4",
    title: "Raja Raja Chozhan",
    titleTa: "ராஜ ராஜ சோழன்",
    movie: "Rettai Vaal Kuruvi",
    year: 1987,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "VM7GcOKCeq4",
    title: "Kakki Sattai Potta Machan",
    titleTa: "காக்கி சட்டை போட்ட மச்சான்",
    movie: "Sankar Guru",
    year: 1987,
    composer: "Chandrabose",
    era: "80s",
    vibe: "kuthu",
  },
  {
    youtubeId: "A3WoJOjbWQE",
    title: "Kannukkul Nooru Nilava",
    titleTa: "கண்ணுக்குள் நூறு நிலவா",
    movie: "Vedham Pudhithu",
    year: 1987,
    composer: "Devendran",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "eZI7kQmfu7c",
    title: "Ninnukori Varnam",
    titleTa: "நின்னுக்கோரி வர்ணம்",
    movie: "Agni Natchathiram",
    year: 1988,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "LQOAAfhCeLM",
    title: "Oru Poongavanam",
    titleTa: "ஒரு பூங்காவனம்",
    movie: "Agni Natchathiram",
    year: 1988,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "U3GjGou8KuI",
    title: "Vaa Vaa Anbe Anbe",
    titleTa: "வா வா அன்பே அன்பே",
    movie: "Agni Natchathiram",
    year: 1988,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "ow2Jm00HZe8",
    title: "Thenmadurai Vaigai Nadhi",
    titleTa: "தென்மதுரை வைகை நதி",
    movie: "Dharmathin Thalaivan",
    year: 1988,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "7K52W44bCAE",
    title: "Valaiyosai Kala Kalavena",
    titleTa: "வளையோசை கலகலவென",
    movie: "Sathya",
    year: 1988,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "hbDgMzcbg80",
    title: "Vaazhavaikkum Kadhalukku",
    titleTa: "வாழவைக்கும் காதலுக்கு",
    movie: "Apoorva Sagodharargal",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "4yaHQisjqAY",
    title: "Indha Maan",
    titleTa: "இந்த மான்",
    movie: "Karakattakkaran",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "FYLM3LXfS8s",
    title: "Kudagu Malai",
    titleTa: "குடகு மலை",
    movie: "Karakattakkaran",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "OW8vCfH_3I0",
    title: "Maanguyilae Poonguyilae",
    titleTa: "மாங்குயிலே பூங்குயிலே",
    movie: "Karakattakkaran",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "9yTRkVngiRk",
    title: "Ooruvittu Ooruvandhu",
    titleTa: "ஊரு விட்டு ஊரு வந்து",
    movie: "Karakattakkaran",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "folk",
  },
  {
    youtubeId: "YkWIc_f_AR0",
    title: "Maama Un Ponna Kodu",
    titleTa: "மாமா உன் பொண்ண கொடு",
    movie: "Rajadhi Raja",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "kuthu",
  },
  {
    youtubeId: "jlh8r38x8Jc",
    title: "Meenamma Meenamma",
    titleTa: "மீனம்மா மீனம்மா",
    movie: "Rajadhi Raja",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "kuthu",
  },
  {
    youtubeId: "T45wKbo30_Q",
    title: "Vaa Vaa Manjal Malare",
    titleTa: "வா வா மஞ்சள் மலரே",
    movie: "Rajadhi Raja",
    year: 1989,
    composer: "Ilaiyaraaja",
    era: "80s",
    vibe: "melody",
  },
  {
    youtubeId: "x7vdB_7I5Uw",
    title: "Nee Pathi Naan Pathi",
    titleTa: "நீ பாதி நான் பாதி",
    movie: "Keladi Kanmani",
    year: 1990,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "LWCG06X6D00",
    title: "Pachamala Poovu",
    titleTa: "பச்சமலை பூவு",
    movie: "Kizhakku Vaasal",
    year: 1990,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "ajMGP__XJng",
    title: "Kalyana Then Nila",
    titleTa: "கல்யாண தேன் நிலா",
    movie: "Mounam Sammadham",
    year: 1990,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "vxbi1ay_u2o",
    title: "Chinna Ponnuthan",
    titleTa: "சின்ன பொண்ணுதான்",
    movie: "Vaigasi Poranthachu",
    year: 1990,
    composer: "Deva",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "rzDJiv1UQjo",
    title: "Pasamulla Pandiyare",
    titleTa: "பாசமுள்ள பாண்டியரே",
    movie: "Captain Prabhakaran",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "qCb6Yp49plI",
    title: "Aracha Santhanam",
    titleTa: "அரைச்ச சந்தனம்",
    movie: "Chinna Thambi",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "CqQEqHyZDPE",
    title: "Thooliyile Aada Vandha",
    titleTa: "தூளியிலே ஆட வந்த",
    movie: "Chinna Thambi",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "QahWDBA2Kd0",
    title: "Annan Enna Thambi Enna",
    titleTa: "அண்ணன் என்ன தம்பி என்ன",
    movie: "Dharma Durai",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "c1mzHbdLcBU",
    title: "Santhaikku Vantha Kili",
    titleTa: "சந்தைக்கு வந்த கிளி",
    movie: "Dharma Durai",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "qZ47r-72iVQ",
    title: "Kuyil Paattu",
    titleTa: "குயில் பாட்டு",
    movie: "En Rasavin Manasile",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "hf6IPXb469o",
    title: "Pen Manasu Azham Endru",
    titleTa: "பெண் மனசு ஆழம் என்று",
    movie: "En Rasavin Manasile",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "GYJ6WplDguQ",
    title: "Idhayame Idhayame",
    titleTa: "இதயமே இதயமே",
    movie: "Idhayam",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "Sm-NNZ56vTw",
    title: "Pottu Vaitha Oru Vatta Nila",
    titleTa: "பொட்டு வைத்த ஒரு வட்ட நிலா",
    movie: "Idhayam",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "XTGta2sC5h8",
    title: "Karutha Machan",
    titleTa: "கருத்த மச்சான்",
    movie: "Pudhu Nellu Pudhu Naathu",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "Unx6AgtKrzY",
    title: "Kaattukuyilu Manasukkulla",
    titleTa: "காட்டுக்குயிலு மனசுக்குள்ள",
    movie: "Thalapathi",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "sDGIHBnTZnM",
    title: "Rakkamma Kaiya Thattu",
    titleTa: "ராக்கம்மா கையத் தட்டு",
    movie: "Thalapathi",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "7wD4H3rghYU",
    title: "Sundari Kannal Oru Sethi",
    titleTa: "சுந்தரி கண்ணால் ஒரு சேதி",
    movie: "Thalapathi",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "KiEt9WQdn7A",
    title: "Ennai Thottu Alli Konda",
    titleTa: "என்னை தொட்டு அள்ளிக்கொண்ட",
    movie: "Unna Nenachen Pattu Padichen",
    year: 1991,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "siN8Z1B2T8o",
    title: "Rekkai Katti Parakudhu",
    titleTa: "ரெக்கை கட்டி பறக்குது",
    movie: "Annamalai",
    year: 1992,
    composer: "Deva",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "8lga2MpCiF4",
    title: "Vanthenda Paalkaran",
    titleTa: "வந்தேண்டா பால்காரன்",
    movie: "Annamalai",
    year: 1992,
    composer: "Deva",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "68s4zAQjjtE",
    title: "Nila Kaayum Neram",
    titleTa: "நிலா காயும் நேரம்",
    movie: "Chembaruthi",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "Da-YlqwKsUE",
    title: "Antha Vanatha Pola",
    titleTa: "அந்த வானத்த போல",
    movie: "Chinna Gounder",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "Kpxv_niRCyg",
    title: "Koondukkulla Enna Vachu",
    titleTa: "கூண்டுக்குள்ள என்ன வச்சு",
    movie: "Chinna Gounder",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "8js9ADJzYks",
    title: "Muthumani Maalai",
    titleTa: "முத்துமணி மாலை",
    movie: "Chinna Gounder",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "ZRVK3luGfww",
    title: "Enna Maanamulla Ponnu",
    titleTa: "என்ன மனமுள்ள பொண்ணு",
    movie: "Chinna Pasanga Naanga",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "FROvU1enzec",
    title: "Andhiyila Vaanam",
    titleTa: "அந்தியிலே வானம்",
    movie: "Chinnavar",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "y3wr_zyXAKA",
    title: "Amma Endrazhaikkatha",
    titleTa: "அம்மா என்றழைக்காத",
    movie: "Mannan",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "_KFoUQi1mw8",
    title: "Pudhu Routeladan",
    titleTa: "புது ரூட்டுலதான்",
    movie: "Meera",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "mEqnFtla2uE",
    title: "Anbe Nee Enna",
    titleTa: "அன்பே நீ என்ன",
    movie: "Pandian",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "dp0tSJW_xUs",
    title: "Chinna Chinna Aasai",
    titleTa: "சின்னச் சின்ன ஆசை",
    movie: "Roja",
    year: 1992,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "qMwhqeV-NWw",
    title: "Kadhal Rojave",
    titleTa: "காதல் ரோஜாவே",
    movie: "Roja",
    year: 1992,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "87ETLi81OzM",
    title: "Pottu Vaitha Kadhal",
    titleTa: "பொட்டு வைத்த காதல்",
    movie: "Singaravelan",
    year: 1992,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "G95UGUPwwgM",
    title: "Adi Poonkuyile",
    titleTa: "அடி பூங்குயிலே",
    movie: "Aranmanai Kili",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "eG4PWmqD80Q",
    title: "Kadhoram Lolakku",
    titleTa: "காதோரம் லோலாக்கு",
    movie: "Chinna Mappillai",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "IaGp4dN3jxs",
    title: "Aalappol Velappol",
    titleTa: "ஆலப்போல் வேலப்போல்",
    movie: "Ejamaan",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "Edrj4EO_uXE",
    title: "Oru Naalum Unnai Marakkatha",
    titleTa: "ஒரு நாளும் உன்னை மறக்காத",
    movie: "Ejamaan",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "rIcKUVLUAKc",
    title: "Urakka Kathuthu Kozhi",
    titleTa: "உரக்கக் கத்துது கோழி",
    movie: "Ejamaan",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "CG-I7aNLh04",
    title: "Chikku Bukku Rayile",
    titleTa: "சிக்கு புக்கு ரயிலே",
    movie: "Gentleman",
    year: 1993,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "BthWzOAihkk",
    title: "Ottagathai Kattiko",
    titleTa: "ஒட்டகத்தைக் கட்டிக்கோ",
    movie: "Gentleman",
    year: 1993,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "QIJje6xGWJg",
    title: "Usilampatti Penkutty",
    titleTa: "உசிலம்பட்டி பெண்குட்டி",
    movie: "Gentleman",
    year: 1993,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "IQ6orB9du4U",
    title: "Aathangarai Marame",
    titleTa: "ஆத்தங்கரை மரமே",
    movie: "Kizhakku Cheemayile",
    year: 1993,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "7Ph8YMZOGt8",
    title: "Adi Maana Madhuraila",
    titleTa: "அடி மான் மதுரையில",
    movie: "Koyil Kaalai",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "ofRImWhsqgo",
    title: "Nenjukkule Innarendru",
    titleTa: "நெஞ்சுக்குள்ளே இன்னாரென்று",
    movie: "Ponnumani",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "Sz9e7LSkvD0",
    title: "Nandri Sollave Unakku",
    titleTa: "நன்றி சொல்லவே உனக்கு",
    movie: "Udan Pirappu",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "_1h3EN1-pPM",
    title: "Intha Mamanoda Manasu",
    titleTa: "இந்த மாமனோட மனசு",
    movie: "Uthama Raasa",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "hhpzmDOIo8E",
    title: "Oru Kola Kili",
    titleTa: "ஒரு கோல கிளி",
    movie: "Uzhaippali",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "pJ1NQZN_SyY",
    title: "Oru Maina Maina",
    titleTa: "ஒரு மைனா மைனா",
    movie: "Uzhaippali",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "MqJS7A4t3hQ",
    title: "Ennulle Ennulle",
    titleTa: "என்னுள்ளே என்னுள்ளே",
    movie: "Valli",
    year: 1993,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "PjT12Ce0Kw8",
    title: "Mukkala Mukkabla",
    titleTa: "முக்காலா முக்காபுலா",
    movie: "Kadhalan",
    year: 1994,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "qwnSAPl2wl0",
    title: "Pettai Rap",
    titleTa: "பேட்டை ராப்",
    movie: "Kadhalan",
    year: 1994,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "gaana",
  },
  {
    youtubeId: "kZzfFCly2S8",
    title: "Urvasi Urvasi",
    titleTa: "ஊர்வசி ஊர்வசி",
    movie: "Kadhalan",
    year: 1994,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "pm6EP-bIMIU",
    title: "Ennavendru Solvathamma",
    titleTa: "என்னவென்று சொல்வதம்மா",
    movie: "Rajakumaran",
    year: 1994,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "Cvys4wqsoVA",
    title: "Malligai Mottu",
    titleTa: "மல்லிகை மொட்டு",
    movie: "Sakthivel",
    year: 1994,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "g3wNV6Hi0B4",
    title: "Vaadi Vethalai",
    titleTa: "வாடி வெத்தலை",
    movie: "Veera",
    year: 1994,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "vbTWgZdvrcE",
    title: "Erukkanchedi Oram",
    titleTa: "எருக்கஞ்செடி ஓரம்",
    movie: "Santhaikku Vantha Kili",
    year: 1994,
    composer: "Deva",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "S9Jolu4ASxQ",
    title: "Thendral Vandhu",
    titleTa: "தென்றல் வந்து",
    movie: "Avatharam",
    year: 1995,
    composer: "Ilaiyaraaja",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "O8klcliT9G4",
    title: "Andha Arabic Kadaloram",
    titleTa: "அந்த அரபிக் கடலோரம்",
    movie: "Bombay",
    year: 1995,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "WfwCtR1iLFw",
    title: "Kannalanae",
    titleTa: "கண்ணாளனே",
    movie: "Bombay",
    year: 1995,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "4um9usMjMm0",
    title: "Kuluvalilae",
    titleTa: "குலுவலிலே",
    movie: "Muthu",
    year: 1995,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "p7_GDN6r2OY",
    title: "Oruvan Oruvan Mudhalali",
    titleTa: "ஒருவன் ஒருவன் முதலாளி",
    movie: "Muthu",
    year: 1995,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "FHhwzKC_80c",
    title: "Thillana Thillana",
    titleTa: "தில்லானா தில்லானா",
    movie: "Muthu",
    year: 1995,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "M1uREIFm8C8",
    title: "Kalloori Salai",
    titleTa: "கல்லூரி சாலை",
    movie: "Kadhal Desam",
    year: 1996,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "Fhgpf2ikOWY",
    title: "Musthafa Musthafa",
    titleTa: "முஸ்தபா முஸ்தபா",
    movie: "Kadhal Desam",
    year: 1996,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "MTd7TlWwsSA",
    title: "Panju Mittai Seela Katti",
    titleTa: "பஞ்சு மிட்டாய் சீலை கட்டி",
    movie: "Ettupatti Rasa",
    year: 1997,
    composer: "Deva",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "CJe6G3rri8I",
    title: "Thanjavooru Mannu Eduthu",
    titleTa: "தஞ்சாவூரு மண்ணு எடுத்து",
    movie: "Porkkaalam",
    year: 1997,
    composer: "Deva",
    era: "90s",
    vibe: "folk",
  },
  {
    youtubeId: "nRtH3GWcZbc",
    title: "Poovukkul",
    titleTa: "பூவுக்குள்",
    movie: "Jeans",
    year: 1998,
    composer: "A. R. Rahman",
    era: "90s",
    vibe: "melody",
  },
  {
    youtubeId: "bmnQo4-iRKg",
    title: "O Sona",
    titleTa: "ஓ சோனா",
    movie: "Vaali",
    year: 1999,
    composer: "Deva",
    era: "90s",
    vibe: "kuthu",
  },
  {
    youtubeId: "OHu-T6s5_u0",
    title: "Kadhal Sadugudu",
    titleTa: "காதல் சடுகுடு",
    movie: "Alaipayuthey",
    year: 2000,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "tnFUd2C2QbE",
    title: "Megam Karukkuthu",
    titleTa: "மேகம் கருக்குது",
    movie: "Kushi",
    year: 2000,
    composer: "Deva",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "a73eydgJkMo",
    title: "Kaatre En Vaasal",
    titleTa: "காற்றே என் வாசல்",
    movie: "Rhythm",
    year: 2000,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "1xE054BDd4U",
    title: "Nadhiye Nadhiye",
    titleTa: "நதியே நதியே",
    movie: "Rhythm",
    year: 2000,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "DiNelqnr618",
    title: "Allu Allu",
    titleTa: "அள்ளு அள்ளு",
    movie: "Bagavathi",
    year: 2002,
    composer: "Deva",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "u_RDDr4-Lb4",
    title: "Oh Podu",
    titleTa: "ஓ போடு",
    movie: "Gemini",
    year: 2002,
    composer: "Bharadwaj",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "RmpEMLw3fhw",
    title: "Ale Ale",
    titleTa: "ஆலே ஆலே",
    movie: "Boys",
    year: 2003,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "ErWAMkF6EIs",
    title: "Aasai Aasai",
    titleTa: "ஆசை ஆசை",
    movie: "Dhool",
    year: 2003,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "RojCThu-MdU",
    title: "Kadhal Vandhal",
    titleTa: "காதல் வந்தால்",
    movie: "Iyarkai",
    year: 2003,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "q92qnqIMkZs",
    title: "Ennai Konjam Maatri",
    titleTa: "என்னை கொஞ்சம் மாற்றி",
    movie: "Kaakha Kaakha",
    year: 2003,
    composer: "Harris Jayaraj",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "qkDPwWevS6s",
    title: "Uyirin Uyirae",
    titleTa: "உயிரின் உயிரே",
    movie: "Kaakha Kaakha",
    year: 2003,
    composer: "Harris Jayaraj",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "NA4ikwU3R9I",
    title: "Manmatha Raasa",
    titleTa: "மன்மத ராசா",
    movie: "Thiruda Thirudi",
    year: 2003,
    composer: "Dhina",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "rHuiaFWUtxk",
    title: "Azhagooril Poothavale",
    titleTa: "அழகூரில் பூத்தவளே",
    movie: "Thirumalai",
    year: 2003,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "i1BqRYMFS08",
    title: "Appadi Podu",
    titleTa: "அப்படி போடு",
    movie: "Ghilli",
    year: 2004,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "L1MLc8GvSLQ",
    title: "Kokkara Kokkarako",
    titleTa: "கொக்கரக்கோ கொக்கரக்கோ",
    movie: "Ghilli",
    year: 2004,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "w9J3KfloL14",
    title: "Sha La La",
    titleTa: "ஷா லா லா",
    movie: "Ghilli",
    year: 2004,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "j81MK4srrlY",
    title: "Kandaen Kandaen",
    titleTa: "கண்டேன் கண்டேன்",
    movie: "Madhurey",
    year: 2004,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "iy2mwqAKhxg",
    title: "Andangkaka Kondakari",
    titleTa: "அண்டங்காக்கா கொண்டக்காரி",
    movie: "Anniyan",
    year: 2005,
    composer: "Harris Jayaraj",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "xd9wF3OGLQo",
    title: "Kokku Para Para",
    titleTa: "கொக்கு பறபற",
    movie: "Chandramukhi",
    year: 2005,
    composer: "Vidyasagar",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "U3uiWEOdudQ",
    title: "Kanmoodi Thirakkumbothu",
    titleTa: "கண்மூடித் திறக்கும்போது",
    movie: "Sachein",
    year: 2005,
    composer: "Devi Sri Prasad",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "d8DKbrYUbFA",
    title: "Vaadi Vaadi",
    titleTa: "வாடி வாடி",
    movie: "Sachein",
    year: 2005,
    composer: "Devi Sri Prasad",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "NVey7a5XiTk",
    title: "Dhavanipotta Deepavali",
    titleTa: "தாவணிபோட்ட தீபாவளி",
    movie: "Sandakozhi",
    year: 2005,
    composer: "Yuvan Shankar Raja",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "167wfLSKbh0",
    title: "Ketta Kodukkira Boomi",
    titleTa: "கேட்ட கொடுக்கிற பூமி",
    movie: "Sandakozhi",
    year: 2005,
    composer: "Yuvan Shankar Raja",
    era: "2000s",
    vibe: "folk",
  },
  {
    youtubeId: "_qnAr47jqg4",
    title: "Nee Entha Ooru",
    titleTa: "நீ எந்த ஊரு",
    movie: "Thirupaachi",
    year: 2005,
    composer: "Dhina",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "sFoLmT_pcLQ",
    title: "Oru Naalil",
    titleTa: "ஒரு நாளில்",
    movie: "Pudhupettai",
    year: 2006,
    composer: "Yuvan Shankar Raja",
    era: "2000s",
    vibe: "gaana",
  },
  {
    youtubeId: "eqx85VRgaVU",
    title: "Kummi Adi",
    titleTa: "கும்மி அடி",
    movie: "Sillunu Oru Kadhal",
    year: 2006,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "folk",
  },
  {
    youtubeId: "rp3_FhRnIRw",
    title: "Munbe Vaa",
    titleTa: "முன்பே வா",
    movie: "Sillunu Oru Kadhal",
    year: 2006,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "qqE1TsV_b9c",
    title: "New York Nagaram",
    titleTa: "நியூயார்க் நகரம்",
    movie: "Sillunu Oru Kadhal",
    year: 2006,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "sYmrTTVWBEo",
    title: "My Name Is Billa",
    titleTa: "மை நேம் இஸ் பில்லா",
    movie: "Billa",
    year: 2007,
    composer: "Yuvan Shankar Raja",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "zKBY8iffWl0",
    title: "Iyayyo",
    titleTa: "ஐயய்யோ",
    movie: "Paruthiveeran",
    year: 2007,
    composer: "Yuvan Shankar Raja",
    era: "2000s",
    vibe: "folk",
  },
  {
    youtubeId: "dvZjQLAjdFM",
    title: "Balleilakka",
    titleTa: "பள்ளேலக்கா",
    movie: "Sivaji",
    year: 2007,
    composer: "A. R. Rahman",
    era: "2000s",
    vibe: "folk",
  },
  {
    youtubeId: "zMs-VMzDCtE",
    title: "Naakka Mukka",
    titleTa: "நாக்கா முக்கா",
    movie: "Kadhalil Vizhunthen",
    year: 2008,
    composer: "Vijay Antony",
    era: "2000s",
    vibe: "kuthu",
  },
  {
    youtubeId: "FzLpP8VBC6E",
    title: "Nenjukkul Peidhidum",
    titleTa: "நெஞ்சுக்குள் பெய்திடும்",
    movie: "Vaaranam Aayiram",
    year: 2008,
    composer: "Harris Jayaraj",
    era: "2000s",
    vibe: "melody",
  },
  {
    youtubeId: "IngvLGgX-YU",
    title: "Adada Mazhaida",
    titleTa: "அடடா மழைடா",
    movie: "Paiya",
    year: 2010,
    composer: "Yuvan Shankar Raja",
    era: "2000s",
    vibe: "melody",
  },
];
